### ISSUE TITLE
Does not run on Raspberry Pi 4

### ISSUE THREAD

**Issue by conrad82** [archivy/archivy-docker#9]
I am unable to run archivy through docker-compose on Raspberry Pi 4.
It runs fine if I install it directly on the RPi using `pip3 install archivy`

I am running ubuntu server 20.10 (64-bit). 
Since it runs outside docker, I suspect it is related to the Dockerfile, but I am not able to see the cause. 

I get the following error in the docker logs: 
`archivy_1        | standard_init_linux.go:211: exec user process caused "exec format error"`

Elasticsearch is running fine.
Snippet of my docker-compose.yml file below
(I also run other containers not shown. The container is exposed through a Caddy reverse proxy):
```
version: '3.4'
services:

  archivy:
  # https://github.com/archivy/archivy-docker/blob/main/docker-compose.yml
    image: uzayg/archivy:v1.0.0
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=0
      - ELASTICSEARCH_ENABLED=1
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    volumes:
      - ./archivy/data:/archivy/data
      - ./archivy/config:/archivy/.local/share/archivy
  elasticsearch:
    image: elasticsearch:7.9.0
    restart: unless-stopped
    volumes:
      - ./archivy/elasticsearch/data:/usr/share/elasticsearch/data:rw
    environment:
      - "discovery.type=single-node"
```

Reading a bit in your repository, I see an [issues note](https://github.com/archivy/archivy-docker/blob/main/issues.md) that it does not work on arm due to pandoc is missing. I am able to install pandoc on ubuntu server on the raspberry pi using apt. Is this issue related to base image being alpine? Not sure if it is related to the error though..
